### ISSUE TITLE
Doku doesn't compile on stable Rust

### ISSUE THREAD

**Issue by Nutomic** [anixe/doku#11]
```
$ cargo +stable --version
cargo 1.55.0 (32da73ab1 2021-08-23)

$ cargo +stable check
Compiling proc-macro2 v1.0.29
Compiling syn v1.0.77
Compiling unicode-xid v0.2.2
Compiling version_check v0.9.3
Compiling fnv v1.0.7
Compiling strsim v0.10.0
Compiling ident_case v1.0.1
Compiling serde_derive v1.0.130
Compiling serde v1.0.130
Compiling anyhow v1.0.44
Compiling proc-macro-error-attr v1.0.4
Compiling proc-macro-error v1.0.4
Checking quote v1.0.9
Checking darling_core v0.13.0
Checking doku-test v0.0.0 (/home/felix/workspace/doku/doku-test)
error[E0554]: `#![feature]` may not be used on the stable release channel
--> /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/darling_core-0.13.0/src/lib.rs:2:38
|
2 | #![cfg_attr(feature = "diagnostics", feature(proc_macro_diagnostic))]
|                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `darling_core` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Disabling the "diagnostics" feature of darling_core fixes the problem. Could you please make a patch release with that change? :)

**Comment by Patryk27** [comment]
Hi, thanks for reporting - I've just released 0.10.1 which works on stable 1.51+ 🙂
